name: CI/CD Pipeline

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List repository files
        run: ls -R

      - name: Navigate to project directory
        run: cd subdirectory # Substitua 'subdirectory' pelo diretório correto, ou remova se estiver na raiz.

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "package.json not found in the current directory."
            exit 1
          fi

      - name: Run tests
        run: |
          if [ -f package.json ]; then
            npm test
          else
            echo "package.json not found. Cannot run tests."
            exit 1
          fi
